### ISSUE TITLE
Some fields are read incorrectly

### ISSUE THREAD

**Issue by Astronomie** [mcorega/MySqlSwiftNative#1]
Good work! I'm very excited!
Since I am a beginne in programming, I'm making a few mistakes! So maybe the error is on my side :-)

I have a mySQL table all works fine! but the fields:

Mail is : =gpeinelt,OU=Users,OU=EMEA,DC=global,DC=publicisgroupe,DC=net\x1fgerald.peinelt@r"	Some

SID is : \x06\x1c

DN is : 5-21-2414005191-2431363525-1628603290-15341?C

HFMcode is : "empty"

Created is:   Some
payload_data_0	Builtin.RawPointer	0x4	0x0000000000000004
payload_data_1	Builtin.RawPointer	0x0	0x0000000000000000
payload_data_2	Builtin.RawPointer	0x0	0x0000000000000000
instance_type	Builtin.RawPointer	0x10b4ef308

Expires is :   Some
payload_data_0	Builtin.RawPointer	0xdd	0x00000000000000dd
payload_data_1	Builtin.RawPointer	0x0	0x0000000000000000
payload_data_2	Builtin.RawPointer	0x0	0x0000000000000000
instance_type	Builtin.RawPointer	0x10b4ef308

The fields in the mySQL Database are:

Mail is: gerald.peinelt@resources-de.com
SID is: S-1-5-21-2414005191-2431363525-1628603290-15341
DN is : CN=gpeinelt,OU=Users,OU=EMEA,DC=global,DC=publicisgroupe,DC=net
HFMcode is : DE2607
Created is : 2013-06-28
Express is :  0000-00-00

Can you help me ?

greetings
Gerry

![bildschirmfoto 2016-01-06 um 16 01 38](https://cloud.githubusercontent.com/assets/3813015/12145511/e12f7cca-b48e-11e5-9eb5-425b8975ed12.png)

and i use this part of program:

let con = MySQL.Connection()
        do {
 
        try con.open("XXX.XXX.XXX.XXX", user: "Username", passt: "Password")
            
        try con.use("dbedv")       
        try con.exec("set names utf8")
            
        let select_stmt = try con.prepare("SELECT * FROM tbadinfo WHERE HFMcode = ?")

         let res = try select_stmt.query(["DE9147"])
         var rows = try res.readAllRows()
    
            let arrayNames = rows![0][0]
            
            let datensatz = arrayNames
            
            for (key,value) in datensatz {
               
                print("Feldname: \(key) = \(value!)")

            }
            try con.close()
        } catch {
            print("Fehler: \(error)") 
        }

**Comment by mcorega** [comment]
Hello Gerry,
I just pushed the latest changes to github. I guess your problem was related to the date fields not being read correctly. It should work now. I also implemented unit testing for the OS X target which all pass now. Checkout the latest sources and see if it works for, if not please let me now. 
kindly,
marius

**Comment by Astronomie** [comment]
Hello Marius,

thank you for the fast fix!
So far I use cocoapods only. Can you update your new version also on cocoapods ?
I still don't really understand the installation via Carthage :-(

Thank you in advance

greetings
Gerry

**Comment by mcorega** [comment]
Hallo Gerry,

just updated cocoapods to version 1.0.9. Try to see if it works.

greetings
Marius
